const GET_ASSETS = "GET_ASSETS";
const GET_ASSETS_IN_PROGRESS = "GET_ASSETS_IN_PROGRESS";
const GET_ASSETS_SUCCESS = "GET_ASSETS_SUCCESS";
const GET_ASSETS_FAILED = "GET_ASSETS_FAILED";

export {
  GET_ASSETS,
  GET_ASSETS_IN_PROGRESS,
  GET_ASSETS_SUCCESS,
  GET_ASSETS_FAILED,
};
